"""cycle 2 schema baseline

Revision ID: 0001_cycle2
Revises: 
Create Date: 2026-09-27 19:34:33.213047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_cycle2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rating_scale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('min_value', sa.Integer(), nullable=False),
    sa.Column('max_value', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint('max_value > min_value', name='ck_scale_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('subject_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('rating_band',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scale_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=40), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('font_hex', sa.String(length=7), nullable=False),
    sa.Column('rag', sa.String(length=5), nullable=False),
    sa.Column('meaning', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scale_id'], ['rating_scale.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scale_id', 'lower_bound')
    )
    op.create_table('scorecard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('subject_type_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=120), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_template', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['subject_type_id'], ['subject_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('scorecard_version',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scorecard_id', sa.Integer(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('rating_scale_id', sa.Integer(), nullable=False),
    sa.Column('target_score', sa.Float(), nullable=False),
    sa.Column('aggregation', sa.String(length=20), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('qtc_enabled', sa.Boolean(), nullable=False),
    sa.Column('based_on_version_id', sa.Integer(), nullable=True),
    sa.Column('change_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retired_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("aggregation in ('weighted_mean','minimum')", name='ck_version_agg'),
    sa.CheckConstraint("status in ('draft','published','retired')", name='ck_version_status'),
    sa.CheckConstraint('max_depth between 1 and 6', name='ck_version_depth'),
    sa.ForeignKeyConstraint(['based_on_version_id'], ['scorecard_version.id'], ),
    sa.ForeignKeyConstraint(['rating_scale_id'], ['rating_scale.id'], ),
    sa.ForeignKeyConstraint(['scorecard_id'], ['scorecard.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scorecard_id', 'version_no')
    )
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('subject_name', sa.String(length=300), nullable=False),
    sa.Column('subject_ref', sa.String(length=120), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('evaluator_type', sa.String(length=10), nullable=False),
    sa.Column('evaluator_name', sa.String(length=120), nullable=True),
    sa.Column('judge_model', sa.String(length=80), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('target_score', sa.Float(), nullable=False),
    sa.Column('time_met', sa.Boolean(), nullable=True),
    sa.Column('cost_met', sa.Boolean(), nullable=True),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('origin', sa.String(length=10), nullable=False),
    sa.Column('origin_ref', sa.String(length=300), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('band_label', sa.String(length=40), nullable=True),
    sa.Column('rag', sa.String(length=5), nullable=True),
    sa.Column('quality_met', sa.Boolean(), nullable=True),
    sa.Column('qtc_green', sa.Boolean(), nullable=True),
    sa.Column('gate_failures', sa.JSON(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voided_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("evaluator_type in ('self','human','llm')", name='ck_eval_type'),
    sa.CheckConstraint("origin in ('app','import')", name='ck_eval_origin'),
    sa.CheckConstraint("status in ('draft','completed','void')", name='ck_eval_status'),
    sa.ForeignKeyConstraint(['version_id'], ['scorecard_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parameter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('aggregation', sa.String(length=20), nullable=False),
    sa.Column('is_critical', sa.Boolean(), nullable=False),
    sa.Column('min_acceptable_score', sa.Float(), nullable=True),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.CheckConstraint("aggregation in ('weighted_mean','minimum')", name='ck_param_agg'),
    sa.CheckConstraint('weight >= 0', name='ck_param_weight'),
    sa.ForeignKeyConstraint(['parent_id'], ['parameter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['version_id'], ['scorecard_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'code')
    )
    op.create_table('evaluation_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('media_type', sa.String(length=100), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=True),
    sa.Column('data_type', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.CheckConstraint("data_type in ('number','percent','count','boolean')", name='ck_metric_type'),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parameter_id', 'code')
    )
    op.create_table('parameter_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.Column('is_leaf', sa.Boolean(), nullable=False),
    sa.Column('judged_score', sa.Float(), nullable=True),
    sa.Column('computed_score', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('score_source', sa.String(length=20), nullable=False),
    sa.Column('not_applicable', sa.Boolean(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('effective_weight', sa.Float(), nullable=True),
    sa.Column('band_label', sa.String(length=40), nullable=True),
    sa.CheckConstraint("score_source in ('judged','metric','override','rollup','not_applicable','pending')", name='ck_result_source'),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameter.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'parameter_id')
    )
    op.create_table('rating_criterion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parameter_id', sa.Integer(), nullable=False),
    sa.Column('score_min', sa.Integer(), nullable=False),
    sa.Column('score_max', sa.Integer(), nullable=False),
    sa.Column('qualitative', sa.Text(), nullable=False),
    sa.Column('quantitative', sa.Text(), nullable=True),
    sa.CheckConstraint('score_max >= score_min', name='ck_criterion_range'),
    sa.ForeignKeyConstraint(['parameter_id'], ['parameter.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_threshold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('min_value', sa.Float(), nullable=True),
    sa.Column('max_value', sa.Float(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metric_value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evaluation_id', sa.Integer(), nullable=False),
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluation.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['metric_id'], ['metric.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evaluation_id', 'metric_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metric_value')
    op.drop_table('metric_threshold')
    op.drop_table('rating_criterion')
    op.drop_table('parameter_result')
    op.drop_table('metric')
    op.drop_table('evaluation_document')
    op.drop_table('parameter')
    op.drop_table('evaluation')
    op.drop_table('scorecard_version')
    op.drop_table('scorecard')
    op.drop_table('rating_band')
    op.drop_table('subject_type')
    op.drop_table('rating_scale')
    # ### end Alembic commands ###
