"""cycle 3 behaviour and tuning

Revision ID: 0002_cycle3
Revises: 0001_cycle2
Create Date: 2026-09-27 19:34:34.656485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002_cycle3'
down_revision: Union[str, Sequence[str], None] = '0001_cycle2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('from_state', sa.String(length=20), nullable=True),
    sa.Column('to_state', sa.String(length=20), nullable=True),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_event_at'), 'audit_event', ['at'], unique=False)
    op.create_index(op.f('ix_audit_event_entity_id'), 'audit_event', ['entity_id'], unique=False)
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('subject_type_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['subject_type_id'], ['subject_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_subject_parent_id'), 'subject', ['parent_id'], unique=False)
    op.create_table('submission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('previous_id', sa.Integer(), nullable=True),
    sa.Column('owner', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=15), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('input_text', sa.Text(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision', sa.String(length=10), nullable=True),
    sa.Column('official_score', sa.Float(), nullable=True),
    sa.Column('official_band', sa.String(length=40), nullable=True),
    sa.Column('official_rag', sa.String(length=5), nullable=True),
    sa.Column('judge_spread_pct', sa.Float(), nullable=True),
    sa.Column('gate_failures', sa.JSON(), nullable=False),
    sa.Column('time_met', sa.Boolean(), nullable=True),
    sa.Column('cost_met', sa.Boolean(), nullable=True),
    sa.Column('qtc_green', sa.Boolean(), nullable=True),
    sa.Column('adjudicated', sa.Boolean(), nullable=False),
    sa.Column('decided_by', sa.String(length=120), nullable=True),
    sa.Column('decision_reason', sa.Text(), nullable=True),
    sa.Column('blocks_project', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.CheckConstraint("decision is null or decision in ('passed','redo')", name='ck_sub_decision'),
    sa.CheckConstraint("status in ('open','in_review','adjudication','decided','withdrawn','cancelled')", name='ck_sub_status'),
    sa.ForeignKeyConstraint(['previous_id'], ['submission.id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['scorecard_version.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'version_id', 'attempt_no')
    )
    op.create_index('ix_submission_decision_owner', 'submission', ['decision', 'owner'], unique=False)
    op.create_index('ix_submission_status', 'submission', ['status'], unique=False)
    op.create_table('version_review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['scorecard_version.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person', sa.String(length=120), nullable=False),
    sa.Column('cause', sa.String(length=12), nullable=False),
    sa.Column('action', sa.String(length=12), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submission_id', sa.Integer(), nullable=True),
    sa.Column('recorded_by', sa.String(length=120), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("action in ('train','reassign','discuss','rescope','none')", name='ck_diag_action'),
    sa.CheckConstraint("cause in ('skill','aptitude','will','allocation')", name='ck_diag_cause'),
    sa.ForeignKeyConstraint(['submission_id'], ['submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Existing rows (Cycle 1-2 pilot databases) need server defaults for the new NOT NULL columns.
    with op.batch_alter_table("evaluation") as b:
        b.add_column(sa.Column("gate_failure_count", sa.Integer(), nullable=False, server_default="0"))
        b.add_column(sa.Column("subject_id", sa.Integer(), nullable=True))
        b.add_column(sa.Column("submission_id", sa.Integer(), nullable=True))
        b.add_column(sa.Column("row_version", sa.Integer(), nullable=False, server_default="1"))
        b.create_foreign_key("fk_evaluation_subject", "subject", ["subject_id"], ["id"])
        b.create_foreign_key("fk_evaluation_submission", "submission", ["submission_id"], ["id"])
        b.create_index("ix_evaluation_status_private", ["status", "is_private"], unique=False)
        b.create_index("ix_evaluation_subject_ref", ["subject_ref"], unique=False)
        b.create_index("ix_evaluation_submission", ["submission_id"], unique=False)
        b.create_index("ix_evaluation_version_status", ["version_id", "status"], unique=False)

    # Backfill: gate_failure_count mirrors the JSON list (portable: done row by row, not with JSON SQL).
    conn = op.get_bind()
    evaluation = sa.table("evaluation", sa.column("id", sa.Integer), sa.column("gate_failures", sa.JSON),
                          sa.column("gate_failure_count", sa.Integer))
    for row_id, failures in conn.execute(sa.select(evaluation.c.id, evaluation.c.gate_failures)).all():
        if failures:
            conn.execute(evaluation.update().where(evaluation.c.id == row_id)
                         .values(gate_failure_count=len(failures)))

    op.create_index(op.f("ix_parameter_parent_id"), "parameter", ["parent_id"], unique=False)
    op.create_index(op.f("ix_parameter_version_id"), "parameter", ["version_id"], unique=False)
    with op.batch_alter_table("scorecard") as b:
        b.add_column(sa.Column("requires_review", sa.Boolean(), nullable=False, server_default=sa.false()))
    with op.batch_alter_table("scorecard_version") as b:
        b.add_column(sa.Column("required_judges", sa.Integer(), nullable=False, server_default="1"))
        b.add_column(sa.Column("judge_tolerance_pct", sa.Float(), nullable=False, server_default="10"))
        b.add_column(sa.Column("require_self_appraisal", sa.Boolean(), nullable=False, server_default=sa.false()))
        b.add_column(sa.Column("is_foundational", sa.Boolean(), nullable=False, server_default=sa.false()))
        b.add_column(sa.Column("row_version", sa.Integer(), nullable=False, server_default="1"))
        # autogenerate cannot see CHECK changes: the lifecycle gained 'in_review' and judges got bounds
        b.drop_constraint("ck_version_status", type_="check")
        b.create_check_constraint("ck_version_status", "status in ('draft','in_review','published','retired')")
        b.create_check_constraint("ck_version_judges", "required_judges between 1 and 5")


def downgrade() -> None:
    with op.batch_alter_table("scorecard_version") as b:
        b.drop_constraint("ck_version_judges", type_="check")
        b.drop_constraint("ck_version_status", type_="check")
        b.create_check_constraint("ck_version_status", "status in ('draft','published','retired')")
        for col in ("row_version", "is_foundational", "require_self_appraisal", "judge_tolerance_pct",
                    "required_judges"):
            b.drop_column(col)
    with op.batch_alter_table("scorecard") as b:
        b.drop_column("requires_review")
    op.drop_index(op.f("ix_parameter_version_id"), table_name="parameter")
    op.drop_index(op.f("ix_parameter_parent_id"), table_name="parameter")
    with op.batch_alter_table("evaluation") as b:
        b.drop_constraint("fk_evaluation_submission", type_="foreignkey")
        b.drop_constraint("fk_evaluation_subject", type_="foreignkey")
        for ix in ("ix_evaluation_version_status", "ix_evaluation_submission", "ix_evaluation_subject_ref",
                   "ix_evaluation_status_private"):
            b.drop_index(ix)
        for col in ("row_version", "submission_id", "subject_id", "gate_failure_count"):
            b.drop_column(col)
    op.drop_table("diagnosis")
    op.drop_table("version_review")
    op.drop_index("ix_submission_status", table_name="submission")
    op.drop_index("ix_submission_decision_owner", table_name="submission")
    op.drop_table("submission")
    op.drop_index(op.f("ix_subject_parent_id"), table_name="subject")
    op.drop_table("subject")
    op.drop_index(op.f("ix_audit_event_entity_id"), table_name="audit_event")
    op.drop_index(op.f("ix_audit_event_at"), table_name="audit_event")
    op.drop_table("audit_event")
